apiVersion: v1
kind: ConfigMap
metadata:
  name: namht4-project3-configmap
data:
  DB_NAME: "postgres"
  DB_USERNAME: "postgres"
  DB_HOST: "psql-postgresql"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
stringData:
  DB_PASSWORD: "mpstk1Kol4"